version: "3"

services:
  install-nuxt:
    image: node:19-alpine
    working_dir: /home/node
    volumes:
      - "./:/home/node"
    command: npm install

  nuxt:
    depends_on:
      install-nuxt:
        condition: service_completed_successfully
    image: node:19-alpine
    environment:
      SUPABASE_URL: ${SUPABASE_URL}
      SUPABASE_KEY: ${SUPABASE_KEY}
      NODE_ENV: development
    ports:
      - "3000:3000"
    user: node
    working_dir: /home/node
    volumes:
      - "./:/home/node"
    command: sh -c "npm run dev"

  mongo:
    image: mongo:5.0.17
    environment:
      # MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_USERNAME: root
      # MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
      MONGO_INITDB_ROOT_PASSWORD: passsword
    ports:
      - "27017:27017"
    volumes:
      - "./mongodb/volumes:/data/db"